---
# Site
repository: thijsvanloef/thijsvanloef.nl
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thijs van Loef
title: DevOps Engineer
email: thijs@loef.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: thijsvanloef
linkedin_username: thijsvanloef

# Additional icon links
additional_links:
  - title: loef.photos
    icon: fa-solid fa-camera
    url: https://loef.photos/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-YFMJ3PQMM1"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A team player who leaves nothing to chance and plans everything down to the last detail.
  A Skilled DevOps engineer who wants to make his life as easy as possible by automating whatever I can.

  Skills: <mark>Docker</mark>, <mark>Monitoring</mark>, <mark>Ansible</mark>, <mark>CI/CD</mark>

content:
  - title: Projects  # Title for the section
    layout: list  # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Palworld Server Docker
        link: https://github.com/thijsvanloef/palworld-server-docker
        # link_text: View on GitHub
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/thijsvanloef/palworld-server-docker
          - title: Documentation for the project
            icon: fa-solid fa-book
            url: https://palworld-server-docker.loef.dev/
        quote: >
          A Docker Container to easily run a Palworld dedicated server.
        description: | # this will include new lines to allow paragraphs
          I started this repository as a way to easily manage a PalWorld server for me and my friends, however it has grown significantly in the span of a few weeks.

          The project has reached over a <mark>100k Pulls</mark> on DockerHub and over <mark>2.2K Stars</mark> on GitHub.

  - title: Experience  # Title for the section
    layout: list  # Type of content section (list/text)
    content:
      - layout: left
        title: SIDN
        link: sidn.nl
        sub_title: DevOps Engineer
        caption: Februari 2023 - Present
        quote: >
          <mark>Terraform</mark> <mark>Ansible</mark> <mark>Hashicorp-stack</mark> <mark>Grafana</mark> <mark>GitLab</mark>
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Yoast
        link: yoast.com
        sub_title: DevOps Engineer
        caption: Februari 2020 - Februari 2023
        quote: >
          <mark>Python</mark> <mark>Elastic Search</mark> <mark>Zabbix</mark> <mark>Grafana</mark> <mark>Bash</mark> <mark>Docker</mark> <mark>Jenkins</mark>
        description: | # this will include new lines to allow paragraphs
            Responsible for maintaining, monitoring and developing development and production systems.

  - title: Education  # Title for the section
    layout: list  # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Radboud University
        caption: 2019
        sub_title: Pre-Master Information Sciences
      - layout: top-middle
        title: HAN University of Applied Sciences
        caption: 2016 - 2020
        sub_title: Bachelor ICT - Infrastructure & Security Management
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
